version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-ionic-react-app
    container_name: ionic-react-app
    ports:
      - "8100:8100"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["ionic", "serve", "--host", "0.0.0.0", "--port", "8100"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
